#!/bin/bash

ACCESS_KEY=$1
SECRET_KEY=$2

aws ecr get-login-password --profile rscadmin | docker login --username AWS --password-stdin 086900566647.dkr.ecr.eu-west-2.amazonaws.com
docker rm 086900566647.dkr.ecr.eu-west-2.amazonaws.com/lambda-create-lambda:latest

docker buildx build --build-arg ACCESS_KEY=$ACCESS_KEY --build-arg SECRET_KEY=$SECRET_KEY --platform linux/amd64 --provenance=false -t lambda-create-lambda:latest .
docker tag lambda-create-lambda:latest 086900566647.dkr.ecr.eu-west-2.amazonaws.com/lambda-create-lambda:latest

docker push 086900566647.dkr.ecr.eu-west-2.amazonaws.com/lambda-create-lambda:latest

aws ecr get-login-password --profile default | docker login --username AWS --password-stdin 111644099040.dkr.ecr.eu-west-2.amazonaws.com
